//! Inter-process protocol between the Diatom backend, the GPUI browser shell,
//! and the GPUI DevPanel.
//!
//! All messages are serialised as JSON with a `method` discriminant and a
//! `params` payload (tagged enum, snake_case). The transport layer is a Unix
//! domain socket; see `transport.rs`.
//!
//! ## Communication directions
//!
//! Three independent channels share the same socket infrastructure:
//!
//! ```text
//! Backend ──BrowserMessage──►  DevPanel
//! DevPanel ──DevPanelMessage──► Backend
//! Shell ──ShellMessage──►      Backend
//! Backend ──BackendToShell──►  Shell
//! ```
//!
//! ## Authentication handshake (P0 security fix — Issue #14)
//!
//! Every new connection on the DevPanel socket must complete a token handshake
//! before any `DevPanelMessage` is accepted. Without this, any same-user
//! process that knows the Diatom PID (readable from `/proc`) can compute the
//! socket path and execute arbitrary JavaScript via `EvalJs`.
//!
//! The sequence is:
//!
//! ```text
//!   DevPanel (BridgeServer)          Backend (BridgeClient)
//!         |                                 |
//!         |<------- TCP/UDS connect --------|
//!         |                                 |
//!         |--- HandshakeMessage::Challenge ->|   (server sends first)
//!         |                                 |
//!         |<-- HandshakeMessage::Response --|   (client replies with token)
//!         |                                 |
//!         |--- HandshakeMessage::Accepted ->|   (or Rejected + close)
//!         |                                 |
//!         |<==== normal message flow ======>|
//! ```
//!
//! The token is generated by the main Diatom backend process at startup via
//! [`generate_auth_token`] and passed to the DevPanel as a CLI argument
//! (`--auth-token <TOKEN>`). The backend holds it in memory for use by
//! [`crate::client::BridgeClient::connect`].

use serde::{Deserialize, Serialize};

/// Monotonically increasing counter used to correlate requests with responses.
pub type RequestId = u64;

/// Maximum time (ms) either side waits for the next handshake frame.
pub const HANDSHAKE_TIMEOUT_MS: u64 = 5_000;

// ── Authentication handshake ──────────────────────────────────────────────────

/// One-shot authentication handshake sent at connection open, before any
/// `BrowserMessage` / `DevPanelMessage` traffic.
///
/// The server (DevPanel / `BridgeServer`) sends `Challenge` first.
/// The client (backend / `BridgeClient`) replies with `Response { token }`.
/// The server validates and sends `Accepted` or `Rejected`.
///
/// Only `Accepted` transitions the connection to the normal message flow.
/// Any other outcome (wrong token, timeout, malformed frame) drops the
/// connection immediately.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "method", content = "params", rename_all = "snake_case")]
pub enum HandshakeMessage {
    /// Sent by `BridgeServer` immediately after accepting the connection.
    /// Signals the client to send its token. Contains no secret data.
    Challenge,
    /// Sent by `BridgeClient` in reply. `token` must match the value
    /// the DevPanel received via `--auth-token` at launch.
    Response { token: String },
    /// Sent by `BridgeServer` when the token validates. Normal message
    /// flow begins after the client receives this frame.
    Accepted,
    /// Sent by `BridgeServer` when validation fails. Connection is closed
    /// immediately after this frame is written.
    Rejected { reason: String },
}

/// Generate a 32-byte cryptographically random auth token (hex-encoded, 64
/// ASCII characters). Used by the main Diatom process before spawning the
/// DevPanel.
///
/// The token is passed to `diatom-devpanel` via `--auth-token <TOKEN>` and
/// stored in the backend's `AppState` for use by `BridgeClient::connect`.
pub fn generate_auth_token() -> String {
    use rand::RngCore;
    let mut bytes = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut bytes);
    hex::encode(bytes)
}

// ── Backend → DevPanel ────────────────────────────────────────────────────────

/// Messages sent from the Diatom backend process to the GPUI DevPanel.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "method", content = "params", rename_all = "snake_case")]
pub enum BrowserMessage {
    /// Open or focus the DevPanel at the given workspace root.
    Open {
        id: RequestId,
        /// Absolute path to the workspace root.
        project_root: String,
    },

    /// Notify the DevPanel that the active page has changed.
    PageNavigated {
        url: String,
        title: String,
        /// Serialised DOM snapshot (tag, id, classes, attributes).
        /// `None` when privacy mode suppresses DOM export.
        dom_snapshot: Option<DomNode>,
    },

    /// Push a console log entry from the webview into the DevPanel.
    ConsoleEntry {
        level: ConsoleLevel,
        text: String,
        source_file: Option<String>,
        source_line: Option<u32>,
    },

    /// Push a network event captured by the request monitor.
    NetworkEvent(NetworkEventPayload),

    /// Respond to a source-file fetch request from the DevPanel.
    SourceFileContent {
        id: RequestId,
        url: String,
        /// UTF-8 source text (JS, CSS, or HTML).
        content: String,
    },

    /// Forward a streaming completion delta from the local AI endpoint.
    SlmCompletion {
        id: RequestId,
        delta: String,
        done: bool,
    },

    /// Forward a micro-agent event to the DevPanel AI overlay.
    AgentEvent(AgentEventPayload),

    /// The backend is shutting down; the DevPanel should save state and exit.
    Shutdown,
}

// ── DevPanel → Backend ────────────────────────────────────────────────────────

/// Messages sent from the GPUI DevPanel to the Diatom backend.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "method", content = "params", rename_all = "snake_case")]
pub enum DevPanelMessage {
    /// Request the source text of a URL (Sources panel).
    FetchSourceFile { id: RequestId, url: String },

    /// Evaluate JavaScript in the current webview page.
    ///
    /// # Security
    /// This message is only accepted after the authentication handshake
    /// completes successfully (see [`HandshakeMessage`]). Connections that
    /// have not sent a valid token never reach this message type.
    EvalJs { id: RequestId, script: String },

    /// Highlight a DOM element in the webview (mirrors the element picker).
    HighlightElement { selector: String },

    /// Request a completion from the local AI endpoint (`:11435`).
    SlmRequest {
        id: RequestId,
        model: String,
        messages: Vec<SlmMessage>,
        stream: bool,
    },

    /// Request the current network-monitor snapshot.
    RequestNetworkLog { id: RequestId },

    /// Open a resolved local file in the external Zed IDE.
    ///
    /// The backend resolves the URL to a local path (`project_root + URL path`),
    /// then spawns `zed <path>:<line>`. If `zed` is not in `PATH`, a notification
    /// is shown; no fallback to a cloud URL is attempted (Axiom 8).
    OpenInZedIde {
        /// Source URL as shown in the Sources panel.
        url: String,
        /// Optional line number to jump to on open.
        line: Option<u32>,
    },

    /// Start a new agent run in the backend runner.
    AgentStart {
        id: RequestId,
        goal: String,
        model: String,
    },

    /// Abort the currently running agent plan.
    AgentAbort { plan_id: u64 },

    /// Deliver a tool-execution result from the JS bridge.
    AgentToolResult {
        plan_id: u64,
        ok: bool,
        output: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        image_b64: Option<String>,
    },

    /// DevPanel is initialised and ready to receive the initial page state.
    Ready,

    /// The user closed the DevPanel window.
    Closed,
}

// ── Shell → Backend ───────────────────────────────────────────────────────────

/// Messages sent from the GPUI browser shell to the Diatom backend.
///
/// The shell owns the visible chrome (tab bar, toolbar, address bar) but holds
/// no browser state of its own. All mutations are forwarded to the backend via
/// this enum and take effect there.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "method", content = "params", rename_all = "snake_case")]
pub enum ShellMessage {
    /// Navigate the active tab to `url`.
    Navigate { url: String },

    /// Open a new tab, optionally pre-loading `url`.
    NewTab { url: Option<String> },

    /// Close the tab identified by `id`.
    CloseTab { id: String },

    /// Make the tab identified by `id` the active tab.
    ActivateTab { id: String },

    /// Navigate the active tab to the previous history entry.
    GoBack,

    /// Navigate the active tab to the next history entry.
    GoForward,

    /// Reload the current page.
    Reload,

    /// Request a full tab-list snapshot. `id` is echoed back in the response.
    QueryTabsState { id: RequestId },
}

// ── Backend → Shell ───────────────────────────────────────────────────────────

/// Messages sent from the Diatom backend to the GPUI browser shell.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "method", content = "params", rename_all = "snake_case")]
pub enum BackendToShell {
    /// Full tab-list snapshot — pushed on every state change and returned in
    /// response to `ShellMessage::QueryTabsState`.
    TabsState {
        /// Echoed request id; `0` for unsolicited push events.
        id: RequestId,
        tabs: Vec<ShellTab>,
        active_id: Option<String>,
        can_back: bool,
        can_fwd: bool,
        loading: bool,
    },

    /// The backend is shutting down; the shell should flush state and exit.
    Shutdown,
}

/// Minimal tab descriptor transmitted to the shell.
///
/// Only the fields needed by the chrome (tab bar, omnibox) are included.
/// Internal fields (DOM snapshot, ZRAM, memory weight) are not transmitted.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShellTab {
    pub id: String,
    pub url: String,
    pub title: String,
    /// Sleep state as a human-readable string: `"awake"`, `"shallow"`, or `"deep"`.
    pub sleep: String,
}

// ── Shared data types ─────────────────────────────────────────────────────────

/// A single node in a serialised DOM tree.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DomNode {
    pub tag: String,
    pub id: Option<String>,
    pub classes: Vec<String>,
    pub attrs: Vec<(String, String)>,
    pub children: Vec<DomNode>,
}

/// Severity level of a browser console message.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ConsoleLevel {
    Log,
    Info,
    Warn,
    Error,
    Debug,
}

/// A single network request/response event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NetworkEventPayload {
    pub id: String,
    pub url: String,
    pub method: String,
    pub status: Option<u16>,
    pub request_bytes: u64,
    pub response_bytes: u64,
    pub latency_ms: u64,
    pub blocked: bool,
    pub timestamp_ms: u64,
}

/// A single message in an AI conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlmMessage {
    pub role: String,
    pub content: String,
}

/// Context snapshot pushed to the Resonance UDS socket for Zed to consume.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResonanceContext {
    pub page_url: String,
    pub page_title: String,
    /// Up to 20 recent console errors.
    pub console_errors: Vec<String>,
    /// DOM root, depth-limited to 3 levels.
    pub dom_root: Option<DomNode>,
    /// Active source file URL and the first 4 KB of its content.
    pub active_source: Option<ActiveSource>,
}

/// A source file reference with a content preview.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActiveSource {
    pub url: String,
    pub snippet: String,
}

// ── Agent event payload ───────────────────────────────────────────────────────

/// Payload for `BrowserMessage::AgentEvent`.
/// Mirrors `diatom_agent::runner::AgentEvent` without adding a crate dependency.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AgentEventPayload {
    PlanReady {
        plan_id: u64,
        steps: Vec<String>,
    },
    ToolCall {
        plan_id: u64,
        step_idx: usize,
        step_desc: String,
        call_json: String,
    },
    StepDone {
        plan_id: u64,
        step_idx: usize,
        output: String,
    },
    Done {
        plan_id: u64,
        summary: String,
    },
    Failed {
        plan_id: u64,
        reason: String,
    },
    StepTimeout {
        plan_id: u64,
        step_idx: usize,
    },
    Cancelled {
        plan_id: u64,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shell_message_navigate_roundtrip() {
        let msg = ShellMessage::Navigate {
            url: "https://example.com".to_owned(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let back: ShellMessage = serde_json::from_str(&json).unwrap();
        matches!(back, ShellMessage::Navigate { .. });
    }

    #[test]
    fn backend_to_shell_tabs_state_roundtrip() {
        let msg = BackendToShell::TabsState {
            id: 42,
            tabs: vec![ShellTab {
                id: "t1".to_owned(),
                url: "https://example.com".to_owned(),
                title: "Example".to_owned(),
                sleep: "awake".to_owned(),
            }],
            active_id: Some("t1".to_owned()),
            can_back: false,
            can_fwd: false,
            loading: false,
        };
        let json = serde_json::to_string(&msg).unwrap();
        let back: BackendToShell = serde_json::from_str(&json).unwrap();
        matches!(back, BackendToShell::TabsState { .. });
    }

    #[test]
    fn shutdown_variants_are_type_distinct() {
        let shell_shutdown = serde_json::to_string(&BackendToShell::Shutdown).unwrap();
        let browser_shutdown = serde_json::to_string(&BrowserMessage::Shutdown).unwrap();
        assert_eq!(shell_shutdown, browser_shutdown);
    }

    /// Handshake Challenge serialises without a `params` key (no payload).
    #[test]
    fn handshake_challenge_serialises_cleanly() {
        let msg = HandshakeMessage::Challenge;
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"challenge\""), "method key wrong: {json}");
        // No token in the challenge — must not leak the secret.
        assert!(
            !json.contains("token"),
            "token must not appear in Challenge: {json}"
        );
    }

    /// Handshake Response carries the token field.
    #[test]
    fn handshake_response_roundtrip() {
        let token = "deadbeef".to_owned();
        let msg = HandshakeMessage::Response {
            token: token.clone(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let back: HandshakeMessage = serde_json::from_str(&json).unwrap();
        match back {
            HandshakeMessage::Response { token: t } => assert_eq!(t, token),
            other => panic!("unexpected variant: {other:?}"),
        }
    }

    /// generate_auth_token produces a 64-character lowercase hex string.
    #[test]
    fn auth_token_format() {
        let tok = generate_auth_token();
        assert_eq!(tok.len(), 64, "expected 64 hex chars, got {}", tok.len());
        assert!(
            tok.chars().all(|c| c.is_ascii_hexdigit()),
            "non-hex chars in token"
        );
    }

    /// Two consecutive tokens must not be identical.
    #[test]
    fn auth_tokens_are_unique() {
        let t1 = generate_auth_token();
        let t2 = generate_auth_token();
        assert_ne!(t1, t2, "two consecutive tokens must differ");
    }
}
