[build]
rustflags = ["-C", "prefer-dynamic=no"]

[profile.release]
panic = "abort"

[profile.release-small]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
