//! `executor.rs` — Execute a single plan step by calling the SLM.
//!
//! The executor's context window is deliberately tiny:
//!
//! ```text
//! ┌──────────────────────────────────────────────────────┐
//! │  SYSTEM  (tool schema + role declaration)  ~300 tok  │
//! │  USER    step description                  ~20 tok   │
//! │  USER    live page state (DOM summary)     ~200 tok  │
//! │  [assistant turns from retries, if any]   ~100 tok   │
//! └──────────────────────────────────────────────────────┘
//! ```
//!
//! Total ≤ ~620 tokens in + ~50 tokens out = well within the 1024-token
//! window that even the smallest 0.5 B Candle models handle reliably.
//!
//! ## Retry loop
//!
//! If the model outputs malformed JSON or an invalid tool call, the executor
//! injects a terse correction message and retries up to `MAX_RETRIES` times
//! within the same logical step. The retry history is included in the context
//! only for the duration of the step (discarded afterwards).

use anyhow::{bail, Context, Result};
use diatom_bridge::slm_adapter::{ChatMessage, DiatomSlmClient};

use crate::tools::{ToolCall, ToolResult, TOOL_SCHEMA_PROMPT};

/// Number of SLM retries allowed per step when the output is malformed.
const MAX_RETRIES: usize = 3;
/// Maximum tokens the executor SLM call may emit.
const EXEC_MAX_TOKENS: u32 = 128;

/// Page context snapshot provided to the executor each turn.
#[derive(Debug, Clone, Default)]
pub struct PageContext {
    /// Current page URL.
    pub url: String,
    /// Page `<title>` text.
    pub title: String,
    /// Compact DOM summary: visible interactive elements only.
    /// Generated by `agent.js` → `extractPageContext()`.
    pub dom_summary: String,
}

impl PageContext {
    /// Render as a compact human-readable string for the SLM.
    pub fn to_prompt_text(&self) -> String {
        let mut out = format!("URL: {}\nTitle: {}\n", self.url, self.title);
        if !self.dom_summary.is_empty() {
            // Truncate at 1 500 chars to bound token usage.
            let summary = if self.dom_summary.len() > 1_500 {
                &self.dom_summary[..1_500]
            } else {
                &self.dom_summary
            };
            out.push_str("Interactive elements:\n");
            out.push_str(summary);
        }
        out
    }
}

/// Ask the SLM what action to perform for `step_desc` given `page_ctx`.
///
/// Returns a validated [`ToolCall`] ready for the JS bridge to execute.
/// Retries automatically on malformed output (up to [`MAX_RETRIES`]).
pub async fn decide(
    client: &DiatomSlmClient,
    step_desc: &str,
    page_ctx: &PageContext,
) -> Result<ToolCall> {
    let system = format!(
        "You are a browser automation agent controlling a real web browser.\n\
         Current step: {step_desc}\n\
         {TOOL_SCHEMA_PROMPT}"
    );

    // Start the conversation with the live page state.
    let mut messages = vec![
        ChatMessage {
            role: "system".into(),
            content: system,
        },
        ChatMessage {
            role: "user".into(),
            content: format!(
                "Here is the current page state:\n{}",
                page_ctx.to_prompt_text()
            ),
        },
    ];

    let mut last_error = String::new();

    for attempt in 0..MAX_RETRIES {
        if attempt > 0 {
            // Append the previous (bad) assistant output and a correction nudge.
            messages.push(ChatMessage {
                role: "assistant".into(),
                content: last_error.clone(),
            });
            messages.push(ChatMessage {
                role: "user".into(),
                content: format!(
                    "That output was invalid ({last_error}). \
                     Reply with ONLY the corrected JSON object, nothing else."
                ),
            });
        }

        let raw = client
            .complete(&messages, Some(EXEC_MAX_TOKENS))
            .await
            .context("executor SLM call")?;

        match ToolCall::from_str(&raw) {
            Ok(call) => {
                if attempt > 0 {
                    log::info!("[agent-executor] recovered on attempt {attempt}");
                }
                return Ok(call);
            }
            Err(e) => {
                log::warn!("[agent-executor] attempt {attempt} parse error: {e}");
                last_error = raw;
            }
        }
    }

    bail!("executor failed after {MAX_RETRIES} attempts; last output: {last_error}")
}

/// Build the short assistant context message after a tool result arrives.
///
/// This is appended to the conversation history *only when the same step
/// loops* (e.g. read_page → process result → decide next action within step).
pub fn format_result_message(call: &ToolCall, result: &ToolResult) -> String {
    let action = serde_json::to_string(call).unwrap_or_default();
    if result.ok {
        format!("Action {action} succeeded. Output: {}", result.output)
    } else {
        format!("Action {action} FAILED. Error: {}", result.output)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn page_context_renders_non_empty() {
        let ctx = PageContext {
            url: "https://example.com/booking".into(),
            title: "Book a flight".into(),
            dom_summary: "button#submit Submit\ninput[name=date] Date field".into(),
        };
        let text = ctx.to_prompt_text();
        assert!(text.contains("https://example.com/booking"));
        assert!(text.contains("Submit"));
    }

    #[test]
    fn page_context_truncates_long_dom() {
        let ctx = PageContext {
            url: "u".into(),
            title: "t".into(),
            dom_summary: "x".repeat(2_000),
        };
        let text = ctx.to_prompt_text();
        assert!(text.len() < 1_650);
    }
}
