//! `runner.rs` — The top-level agent state machine.
//!
//! ## State transitions
//!
//! ```text
//!  Idle
//!   │  AgentRunner::start(goal)
//!   ▼
//!  Planning ──SLM──► steps: Vec<String>
//!   │
//!   ▼
//!  Executing { step_idx }
//!   │  SLM decides tool call
//!   │  → push AgentEvent::ToolCall to Tauri event bus
//!   ▼
//!  WaitingResult { step_idx }
//!   │  ← JS calls cmd_agent_tool_result
//!   │
//!   ├─ tool call is terminal (done/fail) ──────────► Done / Failed
//!   │
//!   └─ non-terminal → Executing { step_idx + 1 }
//!        (if all steps done) ──────────────────────► Done
//! ```
//!
//! ## Cancellation
//!
//! The caller receives an [`AbortHandle`] at startup. Dropping it cancels
//! the running agent cleanly; the JS layer receives a final
//! `AgentEvent::Cancelled` event.
//!
//! ## Timeouts
//!
//! - Planning call: 30 s (SLM must respond within this window)
//! - Per-step execution: 10 s for SLM + 15 s for JS tool execution
//! - A stuck step emits `AgentEvent::StepTimeout` and advances to Failed.

use std::sync::Arc;

use tokio::sync::oneshot;
use tokio::time::{timeout, Duration};
use tokio_util::task::AbortOnDropHandle;

use diatom_bridge::slm_adapter::DiatomSlmClient;

use crate::executor::{self, PageContext};
use crate::planner;
use crate::tools::{ToolCall, ToolResult};

// ── Public event type ─────────────────────────────────────────────────────────

/// Events emitted by the runner and forwarded to the Tauri event bus.
/// The JS layer listens via `window.__TAURI__.listen('agent-event', …)`.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AgentEvent {
    /// Planning succeeded — the full step list is known.
    PlanReady { plan_id: u64, steps: Vec<String> },
    /// Executor has decided on a tool call for the current step.
    /// The JS bridge should execute it and reply via `cmd_agent_tool_result`.
    ToolCall {
        plan_id: u64,
        step_idx: usize,
        step_desc: String,
        call: ToolCall,
    },
    /// Step completed; moving to next.
    StepDone {
        plan_id: u64,
        step_idx: usize,
        output: String,
    },
    /// All steps completed successfully.
    Done { plan_id: u64, summary: String },
    /// Unrecoverable error.
    Failed { plan_id: u64, reason: String },
    /// Step tool call timed out waiting for JS result.
    StepTimeout { plan_id: u64, step_idx: usize },
    /// The agent was aborted by the user or a new `AgentStart`.
    Cancelled { plan_id: u64 },
}

// ── Configuration ─────────────────────────────────────────────────────────────

/// Configuration for one agent run.
pub struct AgentConfig {
    /// Human-readable goal in natural language.
    pub goal: String,
    /// SLM model identifier (passed to `DiatomSlmClient::new`).
    pub model: String,
    /// Monotonically increasing plan ID (generated by caller).
    pub plan_id: u64,
    /// Time allowed for the JS tool bridge to execute one action.
    pub tool_timeout_secs: u64,
}

// ── Shared context (Tauri-agnostic I/O handles) ───────────────────────────────

/// Dependencies injected by the Tauri layer.
///
/// Using a trait object keeps `diatom_agent` free of Tauri imports.
pub trait AgentIo: Send + Sync + 'static {
    /// Emit an [`AgentEvent`] to the frontend.
    fn emit(&self, event: AgentEvent);

    /// Evaluate JavaScript in the active webview.
    /// Used to call `window.diatom_action(...)` from Rust.
    fn eval_js(&self, script: String);

    /// Query the current page state from the webview.
    /// Returns a `PageContext`-compatible JSON string.
    fn request_page_context(&self) -> PageContext;
}

// ── Runner ────────────────────────────────────────────────────────────────────

/// One live agent run.  Construct via [`AgentRunner::start`].
pub struct AgentRunner {
    /// Abort this to cancel the running plan.
    pub abort: AbortOnDropHandle<()>,
    /// Send tool results from JS back into the state machine.
    pub result_tx: Arc<ResultSender>,
}

/// Shared handle used by the Tauri command handler to feed tool results into
/// the running state machine.
pub struct ResultSender {
    tx: tokio::sync::Mutex<Option<oneshot::Sender<ToolResult>>>,
}

impl ResultSender {
    fn new() -> Arc<Self> {
        Arc::new(Self {
            tx: tokio::sync::Mutex::new(None),
        })
    }

    /// Register a one-shot receiver.  Called by the state machine before
    /// emitting each `AgentEvent::ToolCall`.
    async fn arm(&self, tx: oneshot::Sender<ToolResult>) {
        *self.tx.lock().await = Some(tx);
    }

    /// Deliver a result from the Tauri command handler.
    /// Returns `false` if no receiver was waiting (duplicate/stale call).
    pub async fn deliver(&self, result: ToolResult) -> bool {
        let mut guard = self.tx.lock().await;
        if let Some(tx) = guard.take() {
            tx.send(result).is_ok()
        } else {
            false
        }
    }
}

impl AgentRunner {
    /// Spawn the agent state machine as a Tokio task.
    ///
    /// Returns immediately; the task drives the planning and execution loop
    /// and emits [`AgentEvent`]s via `io.emit()`.
    pub fn start(cfg: AgentConfig, io: Arc<dyn AgentIo>) -> Self {
        let result_sender = ResultSender::new();
        let rs_clone = Arc::clone(&result_sender);

        let handle = tokio::spawn(run_agent(cfg, io, rs_clone));
        let abort = AbortOnDropHandle::new(handle);

        AgentRunner {
            abort,
            result_tx: result_sender,
        }
    }
}

// ── State machine ─────────────────────────────────────────────────────────────

async fn run_agent(cfg: AgentConfig, io: Arc<dyn AgentIo>, result_tx: Arc<ResultSender>) {
    let plan_id = cfg.plan_id;
    let tool_timeout = Duration::from_secs(cfg.tool_timeout_secs.max(5).min(60));

    let slm = DiatomSlmClient::new(&cfg.model);

    // ── Phase 1: Planning ────────────────────────────────────────────────────
    log::info!("[agent] plan_id={plan_id} planning goal: {}", cfg.goal);

    let steps = match timeout(Duration::from_secs(30), planner::plan(&slm, &cfg.goal)).await {
        Ok(Ok(s)) => s,
        Ok(Err(e)) => {
            io.emit(AgentEvent::Failed {
                plan_id,
                reason: format!("Planning failed: {e}"),
            });
            return;
        }
        Err(_) => {
            io.emit(AgentEvent::Failed {
                plan_id,
                reason: "Planning timed out (30 s)".into(),
            });
            return;
        }
    };

    log::info!(
        "[agent] plan_id={plan_id} plan ready: {} steps",
        steps.len()
    );
    io.emit(AgentEvent::PlanReady {
        plan_id,
        steps: steps.clone(),
    });

    // ── Phase 2: Execution loop ───────────────────────────────────────────────
    for (step_idx, step_desc) in steps.iter().enumerate() {
        log::info!("[agent] plan_id={plan_id} step {step_idx}: {step_desc}");

        let page_ctx = io.request_page_context();

        // Ask the SLM what action to take.
        let call = match timeout(
            Duration::from_secs(10),
            executor::decide(&slm, step_desc, &page_ctx),
        )
        .await
        {
            Ok(Ok(c)) => c,
            Ok(Err(e)) => {
                io.emit(AgentEvent::Failed {
                    plan_id,
                    reason: format!("Step {step_idx} executor error: {e}"),
                });
                return;
            }
            Err(_) => {
                io.emit(AgentEvent::Failed {
                    plan_id,
                    reason: format!("Step {step_idx} executor timed out"),
                });
                return;
            }
        };

        // Terminal calls don't need a round-trip to JS.
        match &call {
            ToolCall::Done { summary } => {
                io.emit(AgentEvent::Done {
                    plan_id,
                    summary: summary.clone(),
                });
                return;
            }
            ToolCall::Fail { reason } => {
                io.emit(AgentEvent::Failed {
                    plan_id,
                    reason: reason.clone(),
                });
                return;
            }
            _ => {}
        }

        // Arm the result receiver *before* emitting the event to avoid a race.
        let (tx, rx) = oneshot::channel::<ToolResult>();
        result_tx.arm(tx).await;

        // Emit the tool call to the JS bridge.
        io.emit(AgentEvent::ToolCall {
            plan_id,
            step_idx,
            step_desc: step_desc.clone(),
            call: call.clone(),
        });

        // Wait for JS to execute the action and report back.
        let result = match timeout(tool_timeout, rx).await {
            Ok(Ok(r)) => r,
            Ok(Err(_)) => {
                // Sender dropped — JS side crashed or was unloaded.
                io.emit(AgentEvent::Failed {
                    plan_id,
                    reason: format!("Step {step_idx}: result channel closed"),
                });
                return;
            }
            Err(_) => {
                io.emit(AgentEvent::StepTimeout { plan_id, step_idx });
                io.emit(AgentEvent::Failed {
                    plan_id,
                    reason: format!("Step {step_idx}: tool execution timed out"),
                });
                return;
            }
        };

        io.emit(AgentEvent::StepDone {
            plan_id,
            step_idx,
            output: result.output.clone(),
        });

        if !result.ok {
            io.emit(AgentEvent::Failed {
                plan_id,
                reason: format!("Step {step_idx} reported failure: {}", result.output),
            });
            return;
        }
    }

    // All steps completed without a terminal call — treat as done.
    io.emit(AgentEvent::Done {
        plan_id,
        summary: "All steps completed.".into(),
    });
}
